// enneagramAnalysis.ts
const enneagramAnalysis = {
    "Type 1": "The Reformer. Key Characteristics: Perfectionists who love order and have a strong sense of right and wrong. Strengths: Highly principled, responsible, and improvement-focused. Challenges: Can be critical of themselves and others, and struggle with frustration when things aren't perfect. Goals for Development: Type 1s can work on embracing imperfection by recognizing the beauty in flaws and the growth that comes from mistakes. Developing patience and compassion, both for themselves and others, allows them to see that true perfection lies in human uniqueness and the journey of improvement, not in the unattainable ideal of flawlessness.",

    "Type 2": "The Helper. Key Characteristics: Warm-hearted and caring, always looking to meet the needs of others. Strengths: Empathetic, generous, and supportive. Challenges: May neglect their own needs and become overly involved in others' lives. Goals for Development: For Type 2s, developing self-care practices is crucial. They need to understand that helping themselves is not selfish but necessary for helping others effectively. Setting healthy boundaries and learning to say no can empower them to maintain their well-being while still being supportive of others. Recognizing their own needs helps them to help others in a more balanced and healthy way.",

    "Type 3": "The Achiever. Key Characteristics: Success-oriented, excelling at setting and meeting goals. Strengths: Ambitious, energetic, and highly driven. Challenges: May tie their self-worth to achievements and worry about their image. Goals for Development: Type 3s benefit from exploring their identity beyond achievements and success. Focusing on authenticity and what truly brings them joy, apart from external accolades, can be liberating. Cultivating self-acceptance and embracing failures as part of the growth process help them to connect more deeply with themselves and others.",

    "Type 4": "The Individualist. Key Characteristics: Creative and sensitive, with a deep appreciation for beauty and personal expression. Strengths: Emotional depth, creativity, and authenticity. Challenges: Can feel misunderstood and may indulge in melancholy. Goals for Development: Type 4s can aim to balance their emotional intensity by finding stability in their identity that isn't solely based on being unique. Engaging in activities that promote emotional regulation, like mindfulness and grounding exercises, helps them to experience a wider range of emotions in a more balanced way. Cultivating resilience against feelings of inadequacy by recognizing their inherent value is key.",

    "Type 5": "The Investigator. Key Characteristics: Curious and innovative, often with a deep focus on a particular area of interest. Strengths: Insightful, perceptive, and independent. Challenges: Can become detached from their emotions and relationships. Goals for Development: Type 5s can strive to engage more with the world around them, challenging their comfort zones by sharing their knowledge and opening up emotionally. Developing trust in others and in their own capacity to deal with feelings helps them to form deeper connections. Encouraging themselves to participate in group activities can also foster a sense of belonging and community.",

    "Type 6": "The Loyalist. Key Characteristics: Committed and security-oriented, highly value trust and loyalty. Strengths: Reliable, responsible, and hard-working. Challenges: Anxiety and suspicion can be prevalent, making it hard to trust. Goals for Development: Type 6s can work on cultivating inner security and trust, both in themselves and in the world. By recognizing that absolute security is an illusion, they can learn to embrace uncertainty with courage. Practices such as mindfulness and stress reduction techniques can help in managing anxiety, fostering a more trusting and open approach to life.",

    "Type 7": "The Enthusiast. Key Characteristics: Energetic and spontaneous, always seeking new experiences and joys. Strengths: Optimistic, versatile, and adventurous. Challenges: May struggle with commitment and focus, avoiding negative emotions. Goals for Development: Type 7s can benefit from embracing depth and mindfulness in their pursuits, learning to appreciate the moment without always looking for the next thrill. Developing patience and the ability to sit with discomfort can lead to more meaningful experiences and relationships. Cultivating gratitude and finding joy in simplicity are also important steps in their journey.",

    "Type 8": "The Challenger. Key Characteristics: Strong and self-confident, often taking charge of situations. Strengths: Protective, direct, and empowering. Challenges: Can be confrontational and struggle with vulnerability. Goals for Development: Type 8s can learn to use their strength in a more nurturing way, recognizing that vulnerability is not a weakness but a strength. Practicing empathy and listening can open new paths to connecting with others on a deeper level. Finding healthy outlets for their intensity and learning to step back and allow others to lead can also be beneficial for their personal growth.",

    "Type 9": "The Peacemaker. Key Characteristics: Peaceful and easygoing, seeking harmony in their environment. Strengths: Empathetic, supportive, and accepting. Challenges: May avoid conflict to their detriment and neglect their own desires. Goals for Development: Type 9s can aim to assert themselves more, recognizing that their opinions and needs matter. Engaging in practices that promote self-awareness and assertiveness training can help them to express their desires more confidently. Learning to face conflict constructively, rather than avoiding it, allows them to grow and maintain healthier relationships."
};
  
  export default enneagramAnalysis;